[package]
name = "graphics"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "0.3.1"
 clap = { version = "3.2.8", features = ["derive"] }

[[bin]]
name = "main"
src = "src/bin/main.rs"
